CREATE TABLE IF NOT EXISTS "users" (
	-- identifier
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	-- email of the user
	"email" VARCHAR(255) NOT NULL UNIQUE,
	-- password of the user
	"password_hash" VARCHAR(255) NOT NULL,
	-- name of the user
	"name" VARCHAR(100) NOT NULL,
	"created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY("id")
);


COMMENT ON COLUMN "users"."id" IS 'identifier';
COMMENT ON COLUMN "users"."email" IS 'email of the user';
COMMENT ON COLUMN "users"."password_hash" IS 'password of the user';
COMMENT ON COLUMN "users"."name" IS 'name of the user';


CREATE TABLE IF NOT EXISTS "businesses" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"email" VARCHAR(255) NOT NULL UNIQUE,
	"password_hash" VARCHAR(255) NOT NULL,
	"business_name" VARCHAR(150) NOT NULL,
	"description" TEXT NOT NULL,
	"logo_url" VARCHAR(500) NOT NULL,
	"created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "categories" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"name" VARCHAR(100) NOT NULL UNIQUE,
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "promo_codes" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"business_id" INTEGER NOT NULL,
	"code" VARCHAR(50) NOT NULL UNIQUE,
	"name" VARCHAR(150) NOT NULL,
	"description" TEXT NOT NULL,
	"image_url" VARCHAR(500) NOT NULL,
	"discount_value" DECIMAL(10,2) NOT NULL,
	"discount_type" VARCHAR(20) NOT NULL,
	"expiry_date" TIMESTAMP NOT NULL,
	"is_active" BOOLEAN NOT NULL DEFAULT TRUE,
	"created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY("id")
);


CREATE INDEX "promo_codes_index_0"
ON "promo_codes" ("business_id", "code");

CREATE TABLE IF NOT EXISTS "promo_categories" (
	"promo_code_id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"category_id" INTEGER NOT NULL
);



ALTER TABLE "businesses"
ADD FOREIGN KEY("id") REFERENCES "promo_codes"("business_id")
ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "promo_categories"
ADD FOREIGN KEY("promo_code_id") REFERENCES "promo_codes"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "promo_categories"
ADD FOREIGN KEY("category_id") REFERENCES "categories"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;